### ISSUE TITLE
Can't progress past auth screen

### ISSUE THREAD

**Issue by mfoltzgoogle** [Mathieu-R/streamwave#104]
Hi @Mathieu-R, I wanted to check if the comments in https://github.com/w3c/presentation-api/issues/450#issuecomment-391082206 and https://github.com/w3c/presentation-api/issues/450#issuecomment-391260395 were helping you with Presentation API support, and do any further debugging if necessary.

I tried installing and running the application on my own Linux workstation using the instructions in the README.md, but I couldn't progress past the authentication screen - it doesn't allow me to create an account and the Google authentication flow shows an error.

Is there a test account I can use to log in?

I also see that the app is available at https://www.streamwave.be and login seems to work there.

**Comment by Mathieu-R** [comment]
Sure. 
You need to set some environment variables.
You can use a `.env` in developpment.
I modified the readme of the API so it's more clear.
